insert into Edificio (Ubicacion) values ('81 Farwell Crossing');
insert into Edificio (Ubicacion) values ('565 5th Court');
insert into Edificio (Ubicacion) values ('4637 Knutson Crossing');
insert into Edificio (Ubicacion) values ('2 Glendale Court');
insert into Edificio (Ubicacion) values ('51 Packers Trail');
insert into Edificio (Ubicacion) values ('240 Aberg Circle');
insert into Edificio (Ubicacion) values ('10723 Northland Hill');
insert into Edificio (Ubicacion) values ('72 Burning Wood Terrace');
insert into Edificio (Ubicacion) values ('3 Elka Lane');
insert into Edificio (Ubicacion) values ('0473 Columbus Center');
insert into Edificio (Ubicacion) values ('148 Northwestern Point');
insert into Edificio (Ubicacion) values ('8313 Division Junction');
insert into Edificio (Ubicacion) values ('651 Cherokee Parkway');
insert into Edificio (Ubicacion) values ('658 Tennessee Pass');
insert into Edificio (Ubicacion) values ('25589 New Castle Street');
insert into Edificio (Ubicacion) values ('921 Straubel Street');
insert into Edificio (Ubicacion) values ('05475 Hoard Street');
insert into Edificio (Ubicacion) values ('5 Bartelt Road');
insert into Edificio (Ubicacion) values ('511 Hooker Pass');
insert into Edificio (Ubicacion) values ('7145 Fairfield Court');
insert into Edificio (Ubicacion) values ('3 Hintze Avenue');
insert into Edificio (Ubicacion) values ('1 Forster Park');
insert into Edificio (Ubicacion) values ('600 Hoard Hill');
insert into Edificio (Ubicacion) values ('488 Division Hill');
insert into Edificio (Ubicacion) values ('6 Vernon Lane');
insert into Edificio (Ubicacion) values ('6 Declaration Center');
insert into Edificio (Ubicacion) values ('16 Spaight Street');
insert into Edificio (Ubicacion) values ('4542 Golf Terrace');
insert into Edificio (Ubicacion) values ('331 Di Loreto Crossing');
insert into Edificio (Ubicacion) values ('6650 Shoshone Road');
insert into Edificio (Ubicacion) values ('85689 Hallows Crossing');
insert into Edificio (Ubicacion) values ('0850 Maple Wood Pass');
insert into Edificio (Ubicacion) values ('323 Eagle Crest Alley');
insert into Edificio (Ubicacion) values ('1738 Messerschmidt Way');
insert into Edificio (Ubicacion) values ('486 Morrow Center');
insert into Edificio (Ubicacion) values ('812 Twin Pines Crossing');
insert into Edificio (Ubicacion) values ('7 Muir Plaza');
insert into Edificio (Ubicacion) values ('7391 Algoma Terrace');
insert into Edificio (Ubicacion) values ('262 Victoria Road');
insert into Edificio (Ubicacion) values ('60 Ilene Way');
insert into Edificio (Ubicacion) values ('6 Anhalt Road');
insert into Edificio (Ubicacion) values ('1 Mcbride Road');
insert into Edificio (Ubicacion) values ('86 Florence Drive');
insert into Edificio (Ubicacion) values ('25 Reinke Lane');
insert into Edificio (Ubicacion) values ('0 Lakeland Court');
insert into Edificio (Ubicacion) values ('5 Forest Run Court');
insert into Edificio (Ubicacion) values ('104 New Castle Court');
insert into Edificio (Ubicacion) values ('54 Melby Pass');
insert into Edificio (Ubicacion) values ('5 Butternut Junction');
insert into Edificio (Ubicacion) values ('54762 Browning Drive');
insert into Edificio (Ubicacion) values ('81076 Towne Avenue');
insert into Edificio (Ubicacion) values ('16857 South Parkway');
insert into Edificio (Ubicacion) values ('8577 Sage Place');
insert into Edificio (Ubicacion) values ('22 Redwing Pass');
insert into Edificio (Ubicacion) values ('7 Di Loreto Road');
insert into Edificio (Ubicacion) values ('744 Mariners Cove Terrace');
insert into Edificio (Ubicacion) values ('37 Butterfield Avenue');
insert into Edificio (Ubicacion) values ('48872 Eggendart Junction');
insert into Edificio (Ubicacion) values ('50429 1st Park');
insert into Edificio (Ubicacion) values ('251 Burning Wood Terrace');
insert into Edificio (Ubicacion) values ('2260 Memorial Way');
insert into Edificio (Ubicacion) values ('167 Sunnyside Alley');
insert into Edificio (Ubicacion) values ('59586 Stoughton Place');
insert into Edificio (Ubicacion) values ('7 Hudson Pass');
insert into Edificio (Ubicacion) values ('7 Clemons Pass');
insert into Edificio (Ubicacion) values ('6579 Arapahoe Lane');
insert into Edificio (Ubicacion) values ('0238 Stone Corner Circle');
insert into Edificio (Ubicacion) values ('166 Swallow Street');
insert into Edificio (Ubicacion) values ('2409 Kensington Drive');
insert into Edificio (Ubicacion) values ('4261 Forest Dale Street');
insert into Edificio (Ubicacion) values ('5642 Eagle Crest Trail');
insert into Edificio (Ubicacion) values ('03817 Dryden Alley');
insert into Edificio (Ubicacion) values ('5 Crest Line Place');
insert into Edificio (Ubicacion) values ('378 Kipling Lane');
insert into Edificio (Ubicacion) values ('09 Vernon Alley');
insert into Edificio (Ubicacion) values ('0570 Hudson Trail');
insert into Edificio (Ubicacion) values ('55 Walton Lane');
insert into Edificio (Ubicacion) values ('32528 Hermina Drive');
insert into Edificio (Ubicacion) values ('31161 Westend Park');
insert into Edificio (Ubicacion) values ('07355 Kensington Park');
insert into Edificio (Ubicacion) values ('71 Blaine Pass');
insert into Edificio (Ubicacion) values ('4390 Algoma Plaza');
insert into Edificio (Ubicacion) values ('604 Monument Road');
insert into Edificio (Ubicacion) values ('530 Center Avenue');
insert into Edificio (Ubicacion) values ('886 Graedel Road');
insert into Edificio (Ubicacion) values ('6725 Susan Park');
insert into Edificio (Ubicacion) values ('06 International Avenue');
insert into Edificio (Ubicacion) values ('2444 Portage Court');
insert into Edificio (Ubicacion) values ('13 Ryan Place');
insert into Edificio (Ubicacion) values ('7 Bluestem Point');
insert into Edificio (Ubicacion) values ('04 Montana Point');
insert into Edificio (Ubicacion) values ('5 Westend Place');
insert into Edificio (Ubicacion) values ('86748 Pierstorff Pass');
insert into Edificio (Ubicacion) values ('6 Superior Avenue');
insert into Edificio (Ubicacion) values ('41 Hooker Alley');
insert into Edificio (Ubicacion) values ('17217 Bartelt Place');
insert into Edificio (Ubicacion) values ('142 Eggendart Hill');
insert into Edificio (Ubicacion) values ('2 Mifflin Way');
insert into Edificio (Ubicacion) values ('9 Redwing Parkway');
insert into Edificio (Ubicacion) values ('42 Anhalt Terrace');
insert into Edificio (Ubicacion) values ('05 Carpenter Avenue');
insert into Edificio (Ubicacion) values ('3329 Service Hill');
insert into Edificio (Ubicacion) values ('72756 Caliangt Court');
insert into Edificio (Ubicacion) values ('300 7th Center');
insert into Edificio (Ubicacion) values ('35 Mariners Cove Alley');
insert into Edificio (Ubicacion) values ('4500 Randy Hill');
insert into Edificio (Ubicacion) values ('1429 Clyde Gallagher Road');
insert into Edificio (Ubicacion) values ('269 Tomscot Junction');
insert into Edificio (Ubicacion) values ('52573 Commercial Plaza');
insert into Edificio (Ubicacion) values ('0 Schmedeman Circle');
insert into Edificio (Ubicacion) values ('0396 Gina Court');
insert into Edificio (Ubicacion) values ('164 Mariners Cove Way');
insert into Edificio (Ubicacion) values ('66751 Hayes Terrace');
insert into Edificio (Ubicacion) values ('3359 Butternut Hill');
insert into Edificio (Ubicacion) values ('4 Moulton Crossing');
insert into Edificio (Ubicacion) values ('9523 Oxford Trail');
insert into Edificio (Ubicacion) values ('72366 Rieder Plaza');
insert into Edificio (Ubicacion) values ('429 Jackson Lane');
insert into Edificio (Ubicacion) values ('215 Delladonna Lane');
insert into Edificio (Ubicacion) values ('68 Steensland Way');
insert into Edificio (Ubicacion) values ('291 Harbort Pass');
insert into Edificio (Ubicacion) values ('94 Cardinal Pass');
insert into Edificio (Ubicacion) values ('140 Hagan Plaza');
insert into Edificio (Ubicacion) values ('36 Trailsway Crossing');
insert into Edificio (Ubicacion) values ('924 Haas Alley');
insert into Edificio (Ubicacion) values ('59 Eastwood Terrace');
insert into Edificio (Ubicacion) values ('05 Weeping Birch Junction');
insert into Edificio (Ubicacion) values ('953 Waubesa Lane');
insert into Edificio (Ubicacion) values ('62468 Schlimgen Circle');
insert into Edificio (Ubicacion) values ('13891 Truax Point');
insert into Edificio (Ubicacion) values ('76 Beilfuss Junction');
insert into Edificio (Ubicacion) values ('3 Glendale Place');
insert into Edificio (Ubicacion) values ('10870 Hollow Ridge Center');
insert into Edificio (Ubicacion) values ('703 Merry Road');
insert into Edificio (Ubicacion) values ('30074 Monument Drive');
insert into Edificio (Ubicacion) values ('9 Bultman Pass');
insert into Edificio (Ubicacion) values ('5864 Ramsey Plaza');
insert into Edificio (Ubicacion) values ('8 Parkside Trail');
insert into Edificio (Ubicacion) values ('98948 Summer Ridge Terrace');
insert into Edificio (Ubicacion) values ('6039 Glacier Hill Circle');
insert into Edificio (Ubicacion) values ('27 Stang Circle');
insert into Edificio (Ubicacion) values ('63572 Memorial Lane');
insert into Edificio (Ubicacion) values ('670 Debra Place');
insert into Edificio (Ubicacion) values ('671 Namekagon Road');
insert into Edificio (Ubicacion) values ('0415 Northwestern Street');
insert into Edificio (Ubicacion) values ('5754 Mallard Court');
insert into Edificio (Ubicacion) values ('6 Hintze Point');
insert into Edificio (Ubicacion) values ('6031 Hansons Street');
insert into Edificio (Ubicacion) values ('7773 Pleasure Junction');
insert into Edificio (Ubicacion) values ('3 Arapahoe Lane');
insert into Edificio (Ubicacion) values ('29395 Cascade Crossing');
insert into Edificio (Ubicacion) values ('80 Troy Court');
insert into Edificio (Ubicacion) values ('7 Cordelia Circle');
insert into Edificio (Ubicacion) values ('12 Main Pass');
insert into Edificio (Ubicacion) values ('8 Truax Road');
insert into Edificio (Ubicacion) values ('5216 Bartelt Terrace');
insert into Edificio (Ubicacion) values ('0 Thackeray Crossing');
insert into Edificio (Ubicacion) values ('5 Cambridge Road');
insert into Edificio (Ubicacion) values ('9 Judy Trail');
insert into Edificio (Ubicacion) values ('0 Carberry Trail');
insert into Edificio (Ubicacion) values ('2 Hansons Plaza');
insert into Edificio (Ubicacion) values ('678 Fairfield Crossing');
insert into Edificio (Ubicacion) values ('77033 Jackson Hill');
insert into Edificio (Ubicacion) values ('91419 South Street');
insert into Edificio (Ubicacion) values ('13 Delladonna Place');
insert into Edificio (Ubicacion) values ('25957 American Ash Junction');
insert into Edificio (Ubicacion) values ('719 Nancy Center');
insert into Edificio (Ubicacion) values ('4409 Ridgeway Plaza');
insert into Edificio (Ubicacion) values ('9939 Annamark Parkway');
insert into Edificio (Ubicacion) values ('5 Lakeland Road');
insert into Edificio (Ubicacion) values ('4 Kropf Road');
insert into Edificio (Ubicacion) values ('53625 Sutteridge Parkway');
insert into Edificio (Ubicacion) values ('315 Browning Point');
insert into Edificio (Ubicacion) values ('4757 6th Plaza');
insert into Edificio (Ubicacion) values ('192 Tony Junction');
insert into Edificio (Ubicacion) values ('5 Hazelcrest Drive');
insert into Edificio (Ubicacion) values ('1165 Cody Trail');
insert into Edificio (Ubicacion) values ('5048 Mariners Cove Lane');
insert into Edificio (Ubicacion) values ('60 Hintze Trail');
insert into Edificio (Ubicacion) values ('1 Mitchell Parkway');
insert into Edificio (Ubicacion) values ('4534 Hudson Junction');
insert into Edificio (Ubicacion) values ('694 Mendota Crossing');
insert into Edificio (Ubicacion) values ('050 Pepper Wood Point');
insert into Edificio (Ubicacion) values ('1070 Erie Point');
insert into Edificio (Ubicacion) values ('9338 Evergreen Parkway');
insert into Edificio (Ubicacion) values ('120 Birchwood Circle');
insert into Edificio (Ubicacion) values ('9352 Susan Circle');
insert into Edificio (Ubicacion) values ('304 International Crossing');
insert into Edificio (Ubicacion) values ('34193 Merrick Street');
insert into Edificio (Ubicacion) values ('4 Utah Point');
insert into Edificio (Ubicacion) values ('23 Dunning Alley');
insert into Edificio (Ubicacion) values ('163 Almo Court');
insert into Edificio (Ubicacion) values ('61232 Trailsway Trail');
insert into Edificio (Ubicacion) values ('2972 Arrowood Center');
insert into Edificio (Ubicacion) values ('50779 Division Junction');
insert into Edificio (Ubicacion) values ('31097 Forest Run Point');
insert into Edificio (Ubicacion) values ('0 Donald Junction');
insert into Edificio (Ubicacion) values ('252 Lien Way');
insert into Edificio (Ubicacion) values ('694 Butterfield Road');
insert into Edificio (Ubicacion) values ('58 Holy Cross Terrace');
